spring:
  profiles:
    active:
      - dev # 默认使用环境是 dev
---
server:
  port: 8003 # 端口
  max-http-header-size: 4048576
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 服务注册中心服务地址
spring:
  application:
    name: BACK-CONSUMER # 服务名
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
    profiles: dev # 默认使用环境
---
server:
  port: 8003 # 端口
  max-http-header-size: 4048576
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 服务注册中心服务地址
spring:
  application:
    name: BACK-CONSUMER # 服务名
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
    profiles: test # 测试环境